services:
  app:
    image: mainat/app:${TAG_FRONT}
    container_name: MainatApp-frontend
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

  api:
    image: mainat/api:${TAG_BACK}
    container_name: MainatApp-api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${API_DATABASE_URL}
    depends_on:
      - db_api
    networks:
      - app-network
    restart: unless-stopped

  db_api:
    image: postgres:15
    container_name: MainatApp-db-api
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${API_DB_USER}
      - POSTGRES_PASSWORD=${API_DB_PASSWORD:}
      - POSTGRES_DB=${API_DB_NAME:}
    volumes:
      - postgres_data_api:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data_api:
