services:
  app:
    image: mainat/app:${TAG_FRONT}
    container_name: MainatApp-frontend
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

  api:
    image: mainat/api:${TAG_BACK}
    container_name: MainatApp-api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: MainatApp-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-main_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
